"""initial migratio

Revision ID: 56bdae18b666
Revises: None
Create Date: 2015-05-12 20:19:05.836363

"""

# revision identifiers, used by Alembic.
revision = '56bdae18b666'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
