"""initial migration

Revision ID: 299c377cc7e8
Revises: None
Create Date: 2015-05-17 12:24:40.903919

"""

# revision identifiers, used by Alembic.
revision = '299c377cc7e8'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
